services:
  main:
    build: 
      context: .
      dockerfile: ./bin/Dockerfile.python
    container_name: "${COMPOSE_PROJECT_NAME}-main"
    volumes:
      - ./src:/app:rw
    networks:
      - connector
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
  python:
    build: 
      context: .
      dockerfile: ./bin/Dockerfile.python
    container_name: "${COMPOSE_PROJECT_NAME}-python"
    volumes:
      - ./src:/app:rw
    networks:
      - connector

networks:
  connector:
    driver: bridge
