services:
  main:
    build: 
      context: .
      dockerfile: ./bin/Dockerfile.apache
    container_name: "${COMPOSE_PROJECT_NAME}-main"
    restart: "always"
    volumes:
      - ./src/static:/var/www/html:rw
      - ./logs/apache2:/var/log/apache2
    networks:
      - connector
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
  python:
    build: 
      context: .
      dockerfile: ./bin/Dockerfile.python
    restart: "always"
    container_name: "${COMPOSE_PROJECT_NAME}-python"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./src/API:/app:rw
    networks:
      - connector
  mysql:
    build:
      context: .
      dockerfile: "./bin/Dockerfile.mysql"
    container_name: "${COMPOSE_PROJECT_NAME}-mysql"
    restart: "always"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Los_Angeles
    command: --mysql-native-password=ON
    networks:
      - connector

networks:
  connector:
    driver: bridge
