services:
  python:
    build: 
      context: .
      dockerfile: ./bin/Dockerfile.python
    restart: "always"
    container_name: "${COMPOSE_PROJECT_NAME}-python"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DEBUG: ${DEBUG}
    volumes:
      - ./src:/app:rw
    networks:
      - connector
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:5000"
  mysql:
    build:
      context: .
      dockerfile: "./bin/Dockerfile.mysql"
    container_name: "${COMPOSE_PROJECT_NAME}-mysql"
    restart: "always"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Los_Angeles
    command: --mysql-native-password=ON
    networks:
      - connector

networks:
  connector:
    driver: bridge
